kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: router-cronjob-build
  namespace: 1475a9-prod
spec:
  runPolicy: Serial 
  source: 
    git:
      uri: 'https://github.com/3rdmike/routercrontab.git'
      ref: prod
  output: 
    to:
      kind: ImageStreamTag
      name: "router-cronjob-prod:latest"
  strategy:
   type: Docker
