apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronjob-deployment
  labels:
    app: cronjob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cronjob
  template:
    metadata:
      labels:
        app: cronjob
    spec:
      containers:
      - name: cronjob
        image: image-registry.openshift-image-registry.svc:5000/1475a9-prod/router-cronjob-prod
        ports:
        - containerPort: 80
        env:
        - name: OC_TOKEN
          valueFrom:
            secretKeyRef:
              name: pipeline-token-jbr6q
              key: token
        - name: MINIO_URL
          valueFrom:
            secretKeyRef:
              name: cronjob-secret
              key: minio_url
        - name: BUCKET
          valueFrom:
            secretKeyRef:
              name: cronjob-secret
              key: bucket
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-router-datastore-prod
              key: minioAccessKey
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-router-datastore-prod
              key: minioSecretKey

